# Generated by Django 5.2.4 on 2025-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
