# Generated by Django 5.2.4 on 2025-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0003_note_updated_at_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='firstsite.tag'),
        ),
    ]
