# Generated by Django 5.2.6 on 2026-07-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0009_alter_note_id_noteevent_notesend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteversion',
            name='updated_at',
        ),
    ]
